version: '3.2'

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    expose:
      - "6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    env_file: ./config/.env
volumes:
  redis-data:
  redis-conf:
